# Codecov configuration for pytest-jux
# See: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 88%                # Overall project coverage target (raised from 85%)
        threshold: 3%              # Allow 3% drop before failing (stricter than 5%)
        informational: false       # Fail CI if target not met
    patch:
      default:
        target: 85%                # New code must be 85% covered (raised from 80%)
        threshold: 5%              # More lenient for new code (reduced from 10%)
        informational: false       # Fail CI if new code poorly tested

comment:
  layout: "diff, flags, files"     # Show diff, flags, and file list
  behavior: default                # Comment on every PR
  require_changes: false           # Comment even if no coverage changes
  require_base: false              # Comment even on first PR
  require_head: true               # Require head report to comment

ignore:
  - "tests/**/*"                   # Exclude test files from coverage
  - "**/__pycache__/**/*"         # Exclude Python cache
  - "**/site-packages/**/*"       # Exclude dependencies

# Flag-based coverage tracking
flags:
  unittests:
    paths:
      - pytest_jux/
    carryforward: true             # Carry forward previous results if missing
